#!/usr/bin/python
import sys, gc, os, time, math, re
from PyQt4.Qt import *

QW = QWidget

class Viewer(QW):
    def __init__(self, parent, imglist):
        QW.__init__(self, parent)

        bg = QImage(32, 32, QImage.Format_ARGB32)
        dc = QPainter(bg)
        dc.fillRect(0, 0, 32, 32, QColor(96, 96, 96))
        dc.fillRect(0, 0, 16, 16, QColor(128, 128, 128))
        dc.fillRect(16, 16, 16, 16, QColor(128, 128, 128))
        dc = None
        self.bbrush = QBrush(bg)

        self.setFocusPolicy(Qt.StrongFocus)
        self.setFocus()
        self.pan = False
        self.imglist = imglist[:]
        self.setMouseTracking(True)
        self.fullscreen = False
        self.timer = QTimer(self)
        self.connect(self.timer, SIGNAL("timeout()"), self.checkmtime)
        self.timer.start(250)
        self.pos = None
        self.load(0)

    def load(self, index):
        self.imglist[:] = self.imglist[index:] + self.imglist[:index]
        self.img = QImage(self.imglist[0])
        self.scaled = None
        self.imgmtime = os.stat(self.imglist[0]).st_mtime
        self.update()
        gc.collect()

    def checkmtime(self):
        imgmtime = os.stat(self.imglist[0]).st_mtime
        if imgmtime != self.imgmtime:
            self.load(0)

    def resizeEvent(self, e):
        self.zoomAll()
        QW.resizeEvent(self, e)

    def zoomAll(self):
        self.scale = min(float(self.width()) / max(1, self.img.width()),
                         float(self.height()) / max(1, self.img.height()))
        self.tx = (self.width() - self.img.width()*self.scale) / 2
        self.ty = (self.height() - self.img.height()*self.scale) / 2
        self.update()

    def keyPressEvent(self, e):
        if e.key() == Qt.Key_Right:
            w, h = self.img.width(), self.img.height()
            self.load(1)
            if (w, h) != (self.img.width(), self.img.height()):
                self.zoomAll()
        elif e.key() == Qt.Key_Left:
            w, h = self.img.width(), self.img.height()
            self.load(len(self.imglist) - 1)
            if (w, h) != (self.img.width(), self.img.height()):
                self.zoomAll()
        elif e.key() == Qt.Key_1:
            self.setZoom(1)
        elif e.key() == Qt.Key_2:
            self.setZoom(2)
        elif e.key() == Qt.Key_3:
            self.setZoom(3)
        elif e.key() == Qt.Key_4:
            self.setZoom(4)
        elif e.key() in (Qt.Key_Home, Qt.Key_0):
            self.zoomAll()
        elif e.key() in (Qt.Key_Escape, Qt.Key_Q):
            self.parent().deleteLater()
        elif e.key() == Qt.Key_F:
            self.fullscreen = not self.fullscreen
            if self.fullscreen:
                self.parent().showFullScreen()
            else:
                self.parent().showNormal()
        elif e.key() == Qt.Key_R:
            img = QImage(self.img.height(), self.img.width(), QImage.Format_ARGB32)
            img.fill(0)
            dc = QPainter(img)
            dc.rotate(90)
            dc.drawImage(0, -self.img.height(), self.img)
            dc = None
            self.img = img
            self.zoomAll()
            gc.collect()
        self.update()

    def sizeHint(self):
        return QSize(900, 700)

    def setZoom(self, sf):
        if self.pos:
            mx, my = self.pos[0] * self.scale + self.tx, self.pos[1] * self.scale + self.ty
            self.scale = sf
            self.tx = mx - self.pos[0] * self.scale
            self.ty = my - self.pos[1] * self.scale
        else:
            mx, my = self.width()/2, self.height()/2
            lx, ly = (mx - self.tx)/self.scale, (my - self.ty)/self.scale
            self.scale = sf
            self.tx = mx - lx * self.scale
            self.ty = my - ly * self.scale
        self.update()

    def wheelEvent(self, e):
        self.pos = (e.x() - self.tx) / self.scale, (e.y() - self.ty) / self.scale
        sf = self.scale
        d = int(e.delta() / 120)
        while d > 0:
            sf *= 1.2
            d -= 1
        while d < 0:
            sf /= 1.2
            d += 1
        if sf < 0.01:
            sf = 0.01
        if sf > 10000:
            sf = 10000
        self.setZoom(sf)

    def paintEvent(self, e):
        dc = QPainter(self)
        w, h = self.width(), self.height()
        dc.fillRect(0, 0, w, h, QBrush(QColor(64, 64, 64)))

        iw, ih = int(self.img.width()*self.scale), int(self.img.height()*self.scale)
        dc.fillRect(self.tx, self.ty, iw, ih, self.bbrush)
        if self.scale > 1:
            dc.save()
            dc.translate(self.tx, self.ty)
            dc.scale(self.scale, self.scale)
            dc.drawImage(0, 0, self.img)
            dc.restore()
        else:
            if self.scaled is None or self.scaled[0] != self.scale:
                sw = int(self.img.width() * self.scale)
                sh = int(self.img.height() * self.scale)
                simg = self.img.scaled(QSize(sw, sh), Qt.IgnoreAspectRatio, Qt.SmoothTransformation)
                self.scaled = [self.scale, simg]
            dc.drawImage(self.tx, self.ty, self.scaled[1])

        if self.img.isNull():
            name = self.imglist[0] + " (unable to load as image)"
        else:
            name = self.imglist[0] + " (%i x %i x %ibpp = %0.2f MB)" % (
                self.img.width(),
                self.img.height(),
                self.img.depth(),
                self.img.height() * self.img.bytesPerLine() / (1024.0*1024.0))
        if "/" in name:
            name = name[name.rindex("/")+1:]
        y = 16
        dc.setFont(QFont("sans-serif", 11))
        dc.setPen(QPen(QColor(64, 64, 64)))
        dc.drawText(5, y-1, name)
        dc.drawText(5, y+1, name)
        dc.drawText(7, y, name)
        dc.drawText(7, y, name)
        dc.setPen(QPen(QColor(255,255,255)))
        dc.drawText(6, y, name)

    def mousePressEvent(self, e):
        if e.button():
            self.pan = True
            self.px = e.x()
            self.py = e.y()

    def mouseMoveEvent(self, e):
        if self.pan:
            self.tx += e.x() - self.px
            self.ty += e.y() - self.py
            self.px = e.x()
            self.py = e.y()
            self.update()
        self.pos = ((e.x() - self.tx) / self.scale,
                    (e.y() - self.ty) / self.scale)

    def mouseReleaseEvent(self, e):
        if self.pan:
            self.pan = False

class MyDialog(QDialog):
    def __init__(self, parent, imglist):
        QDialog.__init__(self, parent, Qt.Window)
        self.ws = Viewer(self, imglist)
        L = QVBoxLayout(self)
        L.setContentsMargins(0, 0, 0, 0)
        L.addWidget(self.ws)
        self.setModal(True)
        self.show()

if len(sys.argv) == 1:
    print "Missing image file name(s)"
    sys.exit(1)

def smartSort(s):
    return tuple(int(x) if x[0] in "0123456789" else x
                 for x in re.findall("[0-9]+|[^0-9]+", s.upper()))

app = QApplication([])
filelist = sys.argv[1:]
if len(filelist) == 1:
    slash = filelist[0].rindex("/") if "/" in filelist[0] else -1
    fl = []
    supported_extensions = [str(x).lower() for x in QImageReader.supportedImageFormats()]
    fre = re.compile("^.*\\.(" + "|".join(supported_extensions) + ")$")
    for f in os.listdir(filelist[0][:slash+1] + "."):
        if fre.match(f):
            fl.append(filelist[0][:slash+1] + f)
    fl.sort(key = smartSort)
    if filelist[0] in fl:
        i = fl.index(filelist[0])
        filelist = fl if i == 0 else fl[i:] + fl[:i]
aa = MyDialog(None, filelist)
aa.exec_()
aa = None
